HAI
WAZZUP
    I HAS A bool ITZ WIN BTW TROOF
BUHBYE

BOTH OF BOTH OF FAIL AN WIN AN bool BTW FAIL
EITHER OF NOT bool AN NOT bool
WON OF WIN AN bool
NOT bool
ALL OF NOT WIN AN WIN AN FAIL AN bool MKAY
ANY OF WIN AN NOT WIN AN FAIL AN bool MKAY
NOT bool AN NOT bool
KTHXBYE