HAI
WAZZUP
    I HAS A bool ITZ WIN BTW TROOF
BUHBYE

BOTH OF BOTH OF FAIL AN WIN AN bool BTW FAIL
EITHER OF NOT bool AN NOT bool
VISIBLE "EITHER OF NOT bool AN NOT bool IS " IT
VISIBLE WON OF WIN AN bool
NOT bool
ALL OF NOT WIN AN WIN AN FAIL AN bool MKAY
VISIBLE "ALL OF NOT WIN AN WIN AN FAIL AN bool MKAY IS " IT
ANY OF WIN AN NOT WIN AN FAIL AN bool MKAY
NOT bool
KTHXBYE