HAI
  WAZZUP
    I HAS A TEMP ITZ 0 BTW Temp has to be reals
  BUHBYE
  VISIBLE "WHILE LOOP:"
  IM IN YR LOOP_LABEL UPPIN YR TEMP WILE DIFFRINT TEMP AN 10
    VISIBLE TEMP
  IM OUTTA YR LOOP_LABEL
  TEMP R 0

  VISIBLE "UNTIL LOOP:"
  IM IN YR LOOP_LABEL NERFIN YR TEMP TIL BOTH SAEM TEMP AN -10
    VISIBLE TEMP
  IM OUTTA YR LOOP_LABEL

KTHXBYE
