HAI
SUM OF 1 AN SUM OF 3 AN 4
VISIBLE IT
DIFF OF 1 AN 2
VISIBLE IT
QUOSHUNT OF 1 AN 2
VISIBLE IT
PRODUKT OF 1 AN 2
VISIBLE IT
MOD OF 3 AN 3.14
VISIBLE IT
SUM OF QUOSHUNT OF PRODUKT OF 3 AN 4 AN 2 AN 1
VISIBLE IT
BIGGR OF 1 AN 2
VISIBLE IT
SMALLR OF 1 AN 2
VISIBLE IT

KTHXBYE